import {useEffect,useRef,useState,type PointerEvent,type KeyboardEvent} from 'react';
import {createPortal} from 'react-dom';
import {decorations} from './engine';
import {useStore} from './store';
import {outfitDefaults,outfitStyle,type OutfitPosition} from './outfit-position';
type Position={x:number;y:number;scale?:number;z?:number};
type Props={owned:number[];layout:Record<number,Position>;outfit:string[];onChange:(v:Record<number,Position>)=>void;onOutfit:(v:string[])=>void;decoUrls:string[];notice?:string;onDismissNotice?:()=>void};
const items=[['crown','왕관'],['hat','모자'],['glasses','안경'],['bow','리본'],['scarf','목도리']];
const url=(s:string)=>import.meta.env.BASE_URL+s;
export default function ForestStudio({owned,layout,outfit:savedOutfit,onChange:commitLayout,onOutfit:commitOutfit,decoUrls,notice,onDismissNotice}:Props){
 const editorNotice=notice&&<div className="studio-notice" role="status"><span>{notice}</span><button className="text-btn" onClick={onDismissNotice} aria-label="꾸미기 안내 닫기">닫기</button></div>;
 const [outfit,setOutfit]=useState(savedOutfit);
 const savedWearLayout=useStore(s=>s.capyOutfitLayout);
 const [wearLayout,setWearLayout]=useState<Record<string,OutfitPosition>>(savedWearLayout),[wearSelected,setWearSelected]=useState<string|null>(null);
 const pieceDrag=useRef<{item:string;pointer:number;x:number;y:number;origin:OutfitPosition;rect:DOMRect}|null>(null);
 const adjustWear=(item:string,p:Partial<OutfitPosition>)=>setWearLayout(current=>({...current,[item]:{...(current[item]??outfitDefaults[item]),...p}}));
 const movePiece=(e:PointerEvent<HTMLElement>)=>{const drag=pieceDrag.current;if(!drag||drag.pointer!==e.pointerId)return;adjustWear(drag.item,{x:Math.max(-25,Math.min(125,drag.origin.x+(e.clientX-drag.x)/drag.rect.width*100)),y:Math.max(-40,Math.min(110,drag.origin.y+(e.clientY-drag.y)/drag.rect.height*100))})};
 const endPiece=(e:PointerEvent<HTMLElement>,cancel=false)=>{const drag=pieceDrag.current;if(!drag||drag.pointer!==e.pointerId)return;if(cancel)adjustWear(drag.item,drag.origin);pieceDrag.current=null};
 const [wardrobe,setWardrobe]=useState(false),[wardrobeDraft,setWardrobeDraft]=useState(savedOutfit);
 const dressTarget=useRef<HTMLDivElement>(null);
 const wearDrag=useRef<{item:string;pointer:number;x:number;y:number;moved:boolean}|null>(null);
 const suppressWearClick=useRef(false);
 const [wearGhost,setWearGhost]=useState<{item:string;x:number;y:number}|null>(null);
 const [wearMessage,setWearMessage]=useState('');
 useEffect(()=>{if(!wardrobe){wearDrag.current=null;pieceDrag.current=null;setWearGhost(null);setWearMessage('')}},[wardrobe]);
 const startWear=(e:PointerEvent<HTMLImageElement>,item:string)=>{if(e.button!==0||wearDrag.current)return;suppressWearClick.current=false;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);wearDrag.current={item,pointer:e.pointerId,x:e.clientX,y:e.clientY,moved:false}};
 const moveWear=(e:PointerEvent<HTMLImageElement>)=>{const drag=wearDrag.current;if(!drag||drag.pointer!==e.pointerId)return;if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5)return;drag.moved=true;setWearGhost({item:drag.item,x:e.clientX-40,y:e.clientY-40})};
 const endWear=(e:PointerEvent<HTMLImageElement>,cancel=false)=>{const drag=wearDrag.current;if(!drag||drag.pointer!==e.pointerId)return;wearDrag.current=null;setWearGhost(null);suppressWearClick.current=drag.moved;if(cancel||!drag.moved)return;const rect=dressTarget.current?.getBoundingClientRect();if(rect&&e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom){setWardrobeDraft(current=>current.includes(drag.item)?current:[...current,drag.item]);setWearMessage(`${items.find(([item])=>item===drag.item)?.[1]}를 입혔어요.`)}else setWearMessage('몽쉘 위에 놓아 주세요. 옷은 바뀌지 않았어요.')};
 const openWardrobe=()=>{onDismissNotice?.();setWardrobeDraft([...outfit]);setWearLayout(structuredClone(savedWearLayout));setWearSelected(null);setWardrobe(true)};
 const closeWardrobe=()=>{setWardrobe(false);setAnnouncement('옷 꾸미기를 취소하고 숲으로 돌아왔어요.')};
 const saveWardrobe=()=>{useStore.getState().patch({capyOutfitLayout:wearLayout});commitOutfit(wardrobeDraft);setOutfit([...wardrobeDraft]);if(sessionStart.current)sessionStart.current.outfit=[...wardrobeDraft];history.current=history.current.map(entry=>({...entry,outfit:[...wardrobeDraft]}));setWardrobe(false);setAnnouncement('몽쉘의 옷을 저장하고 숲 꾸미기로 돌아왔어요.')};
 const [announcement,setAnnouncement]=useState('');
 const onChange=(value:Record<number,Position>)=>{latest.current=value;setDraft(value)};
 const onOutfit=(value:string[])=>setOutfit(value);
 const [editing,setEditing]=useState(false);
 useEffect(()=>{if(!editing)setOutfit(savedOutfit)},[savedOutfit,editing]);
 const [expanded,setExpanded]=useState(false),[selected,setSelected]=useState<number|null>(null),[draft,setDraft]=useState(layout),[ghost,setGhost]=useState<number|null>(null);
 const panel=useRef<HTMLElement>(null),scene=useRef<HTMLDivElement>(null),ghostNode=useRef<HTMLImageElement>(null),latest=useRef(draft);
 const ghostPoint=useRef({x:0,y:0});
 useEffect(()=>{const layout=wardrobe?wearLayout:savedWearLayout;for(const [item] of items){const p=layout[item]??outfitDefaults[item];panel.current?.style.setProperty(`--wear-${item}-x`,p.x+'%');panel.current?.style.setProperty(`--wear-${item}-y`,p.y+'%');panel.current?.style.setProperty(`--wear-${item}-scale`,String(p.scale))}},[wardrobe,wearLayout,savedWearLayout]);
 const [,refreshBounds]=useState(0);
 useEffect(()=>{if(!scene.current)return;const observer=new ResizeObserver(()=>refreshBounds(n=>n+1));observer.observe(scene.current);return()=>observer.disconnect()},[wardrobe]);
 const gesture=useRef<{id:number;tray:boolean;x:number;y:number;origin:Position;rect:DOMRect;moved:boolean}|null>(null);
 useEffect(()=>{setDraft(layout);latest.current=layout},[layout]);
 const position=(id:number)=>latest.current[id]??{x:82,y:76,scale:1,z:2};
 const history=useRef<Array<{layout:Record<number,Position>;outfit:string[]}>>([]);
 const [undoCount,setUndoCount]=useState(0);
 const sessionStart=useRef<{layout:Record<number,Position>;outfit:string[]}|null>(null);
 useEffect(()=>{if(editing&&!sessionStart.current)sessionStart.current={layout:structuredClone(layout),outfit:[...outfit]};if(!editing)sessionStart.current=null},[editing,layout,outfit]);
 const cancelEditing=()=>{const saved=sessionStart.current;if(saved){onChange(saved.layout);onOutfit(saved.outfit);latest.current=saved.layout;setDraft(saved.layout)}history.current=[];setUndoCount(0);setSelected(null);setEditing(false);setExpanded(false)};
 const remember=()=>{history.current.push({layout:structuredClone(latest.current),outfit:[...outfit]});if(history.current.length>30)history.current.shift();setUndoCount(history.current.length)};
 const undo=()=>{const previous=history.current.pop();if(!previous)return;latest.current=previous.layout;setDraft(previous.layout);onChange(previous.layout);onOutfit(previous.outfit);setSelected(null);setUndoCount(history.current.length)};
 const bound=(id:number,p:Position)=>{const r=scene.current?.getBoundingClientRect();if(!r)return p;const node=scene.current?.querySelector<HTMLElement>(`[data-object="${id}"]`);const ratio=node&&node.offsetWidth?node.offsetHeight/node.offsetWidth:1;const width=(id===-1?18:id>=0?13:16);const scale=Math.min(p.scale??1,94/width,94*r.height/(width*r.width*ratio));const halfX=width*scale/2,halfY=width*scale*r.width*ratio/r.height/2;return {...p,scale,x:Math.max(halfX+2,Math.min(98-halfX,p.x)),y:Math.max(halfY+2,Math.min(98-halfY,p.y))}};
 const name=(id:number)=>id===-1?'몽쉘':id>=0?decorations[id]:items[-id-2][1];
 useEffect(()=>{if(!editing||selected===null)return;const p=position(selected);const timer=setTimeout(()=>setAnnouncement(`${name(selected)} 선택. 왼쪽에서 ${Math.round(p.x)}%, 위에서 ${Math.round(p.y)}%. 크기 ${Math.round((p.scale??1)*100)}%. 겹침 순서 ${p.z??2}.`),200);return()=>clearTimeout(timer)},[editing,selected,draft]);
 const image=(id:number)=>id===-1?url('art/mongshell-front.png'):id>=0?decoUrls[id]:url(`outfit/${items[-id-2][0]}-fitted.png`);
 const update=(id:number,p:Partial<Position>,save=true)=>{const next={...latest.current,[id]:bound(id,{...position(id),...p})};latest.current=next;setDraft(next);if(save)onChange(next)};
 const remove=(id:number)=>{remember();const next={...latest.current};delete next[id];latest.current=next;setDraft(next);onChange(next);setSelected(null)};
 const start=(e:PointerEvent,id:number,tray=false)=>{if(!editing||gesture.current||e.button!==0||!scene.current)return;remember();e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);gesture.current={id,tray,x:e.clientX,y:e.clientY,origin:{...position(id)},rect:scene.current.getBoundingClientRect(),moved:false};if(!tray)setSelected(id)};
 const move=(e:PointerEvent)=>{const g=gesture.current;if(!g)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(!g.moved&&Math.hypot(dx,dy)<5)return;g.moved=true;if(g.tray){ghostPoint.current={x:e.clientX-40,y:e.clientY-40};setGhost(g.id);if(ghostNode.current)ghostNode.current.style.transform=`translate(${ghostPoint.current.x}px,${ghostPoint.current.y}px)`;}else update(g.id,{x:Math.max(5,Math.min(95,g.origin.x+dx/g.rect.width*100)),y:Math.max(8,Math.min(92,g.origin.y+dy/g.rect.height*100))},false)};
 const end=(e:PointerEvent,cancel=false)=>{const g=gesture.current;if(!g)return;gesture.current=null;setGhost(null);if(cancel){if(!g.tray)update(g.id,g.origin);return;}if(g.tray){if(g.moved){const r=scene.current!.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom){update(g.id,{x:(e.clientX-r.left)/r.width*100,y:(e.clientY-r.top)/r.height*100});setSelected(g.id)}}else if(g.id>=0){update(g.id,{x:latest.current[g.id]?.x??50,y:latest.current[g.id]?.y??70});setSelected(g.id)}else{update(g.id,{x:50,y:70});setSelected(g.id)}}else onChange(latest.current)};
 const key=(e:KeyboardEvent,id:number)=>{if(!editing)return;const d:Record<string,[number,number]>={ArrowLeft:[-3,0],ArrowRight:[3,0],ArrowUp:[0,-3],ArrowDown:[0,3]};if(id!==-1&&e.key==='Delete'){e.preventDefault();remove(id)}else if(d[e.key]){remember();e.preventDefault();const p=position(id);update(id,{x:Math.max(5,Math.min(95,p.x+d[e.key][0])),y:Math.max(8,Math.min(92,p.y+d[e.key][1]))})}};
 const reorder=(front:boolean)=>{if(selected===null)return;remember();const ids=[...new Set([...Object.keys(latest.current).map(Number),-1])].sort((a,b)=>(position(a).z??2)-(position(b).z??2)).filter(id=>id!==selected);if(front)ids.push(selected);else ids.unshift(selected);const next={...latest.current};ids.forEach((id,i)=>next[id]={...position(id),z:i+1});latest.current=next;setDraft(next);onChange(next)};
 useEffect(()=>{if(!expanded)return;const previous=document.activeElement as HTMLElement|null,old=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.querySelector<HTMLButtonElement>('button')?.focus();const close=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();if(wardrobe)closeWardrobe();else cancelEditing()}if(e.key==='Tab'){const controls=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,[tabindex="0"]')??[]).filter(el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden');if(!controls.length)return;const first=controls[0],last=controls[controls.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',close);previous?.focus()}},[expanded,wardrobe]);
 const objects=[...Object.keys(draft).map(Number).filter(x=>x!==-1),-1];
 const handlers={onPointerMove:move,onPointerUp:(e:PointerEvent)=>end(e),onPointerCancel:(e:PointerEvent)=>end(e,true)};
 const finishEditing=()=>{if(editing){commitLayout(latest.current);commitOutfit(outfit);setEditing(false);setExpanded(false);history.current=[];setUndoCount(0);}else{setEditing(true);setExpanded(true);}setSelected(null);};
 if(wardrobe)return <section ref={panel} role="dialog" aria-modal="true" aria-labelledby="wardrobe-title" className="forest-studio studio-expanded wardrobe-page">
 <div className="wardrobe-toolbar"><button className="secondary" onClick={closeWardrobe}>취소 · 숲으로</button><button className="primary" onClick={saveWardrobe}>저장하고 숲으로</button></div>
 <h1 id="wardrobe-title">몽쉘 꾸미기</h1><p>소품 그림을 몽쉘 위로 끌어 놓아 봐. 눌러서 입히거나 벗길 수도 있어.</p>
 {editorNotice}
 <div className="wardrobe-preview"><div ref={dressTarget} className="capy-dressup"><img src={url('art/mongshell-front.png')} alt="몽쉘 인형" draggable={false}/><div className="capy-wear">{wardrobeDraft.map(item=><span key={item} style={outfitStyle(item,wearLayout)} className={'wear-'+item+' wearable-piece'+(wearSelected===item?' is-selected':'')} role="button" tabIndex={0} aria-label={`${items.find(([id])=>id===item)?.[1]} 선택 및 이동`} onFocus={()=>setWearSelected(item)} onPointerDown={e=>{if(e.button!==0||pieceDrag.current||!dressTarget.current)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);setWearSelected(item);pieceDrag.current={item,pointer:e.pointerId,x:e.clientX,y:e.clientY,origin:{...(wearLayout[item]??outfitDefaults[item])},rect:dressTarget.current.getBoundingClientRect()}}} onPointerMove={movePiece} onPointerUp={e=>endPiece(e)} onPointerCancel={e=>endPiece(e,true)} onKeyDown={e=>{const delta:Record<string,[number,number]>={ArrowLeft:[-3,0],ArrowRight:[3,0],ArrowUp:[0,-3],ArrowDown:[0,3]};if(delta[e.key]){e.preventDefault();const p=wearLayout[item]??outfitDefaults[item];adjustWear(item,{x:Math.max(-25,Math.min(125,p.x+delta[e.key][0])),y:Math.max(-40,Math.min(110,p.y+delta[e.key][1]))})}else if(e.key==='Delete'){e.preventDefault();setWardrobeDraft(current=>current.filter(id=>id!==item));setWearSelected(null)}else if(e.key==='Enter'||e.key===' '){e.preventDefault();setWearSelected(item)}}}><img src={url(`outfit/${item}-fitted.png`)} alt="" draggable={false}/></span>)}</div></div></div>
 {wearSelected&&wardrobeDraft.includes(wearSelected)&&<div className="wear-adjust"><strong>{items.find(([item])=>item===wearSelected)?.[1]}</strong><label htmlFor="wear-scale">크기 {Math.round((wearLayout[wearSelected]??outfitDefaults[wearSelected]).scale*100)}%</label><input id="wear-scale" aria-valuetext={Math.round((wearLayout[wearSelected]??outfitDefaults[wearSelected]).scale*100)+'퍼센트'} type="range" min="0.5" max="2.5" step="0.1" value={(wearLayout[wearSelected]??outfitDefaults[wearSelected]).scale} onChange={e=>adjustWear(wearSelected,{scale:Number(e.target.value)})}/><button className="secondary" onClick={()=>{setWardrobeDraft(current=>current.filter(item=>item!==wearSelected));setWearSelected(null);setWearMessage('소품을 벗겼어. 목록에서 다시 입힐 수 있어.')}}>벗기기</button></div>}
 <p role="status" aria-live="polite">{wearMessage}</p>
 <div className="wardrobe-options" aria-label="몽쉘 의상">{items.map(([item,label])=><button className="secondary" key={item} aria-pressed={wardrobeDraft.includes(item)} onClick={e=>{if(e.detail!==0&&suppressWearClick.current){suppressWearClick.current=false;return;}setWardrobeDraft(current=>current.includes(item)?current.filter(x=>x!==item):[...current,item]);}}><img src={url(`outfit/${item}-fitted.png`)} alt="" draggable={false} onPointerDown={e=>startWear(e,item)} onPointerMove={moveWear} onPointerUp={e=>endWear(e)} onPointerCancel={e=>endWear(e,true)}/><span>{label}</span><small>{wardrobeDraft.includes(item)?'착용 중':'입히기'}</small></button>)}</div>
 {wearGhost&&createPortal(<img className="studio-drag-ghost" style={{transform:`translate(${wearGhost.x}px,${wearGhost.y}px)`}} src={url(`outfit/${wearGhost.item}-fitted.png`)} alt="" draggable={false}/>,document.body)}
 </section>;
 return <section ref={panel} role={expanded?'dialog':undefined} aria-modal={expanded||undefined} className={'forest-studio'+(expanded?' studio-expanded':'')} aria-label="내 숲 꾸미기"><div className="studio-toolbar">{editing&&<button className="secondary studio-cancel" onClick={cancelEditing}>취소</button>}{!editing&&<button className="secondary studio-expand" aria-pressed={expanded} onClick={()=>{setEditing(true);setExpanded(true)}}>크게 꾸미기</button>}<button className="primary studio-edit" aria-pressed={editing} onClick={finishEditing}>{editing?'저장하기':'숲 꾸미기 시작'}</button>{editing&&<button className="secondary studio-undo" disabled={!undoCount} onClick={undo}>되돌리기</button>}</div><div className="studio-heading"><div><h2>{editing?'물건을 끌어 숲에 놓아 봐':'몽쉘의 작은 숲'}</h2></div>{editing&&<span className="drag-help">물건을 누르면 크기와 앞뒤 순서를 바꿀 수 있어</span>}</div>
 <div className={"studio-scene"+(ghost!==null?" studio-drop-ready":"")} ref={scene} onClick={()=>setSelected(null)}>{objects.map(id=>{const p=bound(id,draft[id]??{x:82,y:76});return <div key={id} data-object={id} className={id===-1?'capy-dressup movable-capy':'free-deco'} style={{left:p.x+'%',top:p.y+'%',right:'auto',bottom:'auto',width:(id===-1?18:id>=0?13:16)*(p.scale??1)+'%',minWidth:0,zIndex:p.z??2,transform:'translate(-50%,-50%)'}} onPointerDown={e=>start(e,id)} {...handlers} onClick={e=>{e.stopPropagation();if(editing)setSelected(id)}} onKeyDown={e=>key(e,id)} onFocus={()=>{if(editing)setSelected(id)}} tabIndex={editing?0:-1} role={editing?'button':undefined} aria-label={editing?`${name(id)} 이동. 방향키로 위치 조정`:name(id)}><img className={'studio-object-image'+(id< -1?' loose-outfit':'')} src={image(id)} alt={name(id)} draggable={false}/>{id===-1&&<div className="capy-wear">{outfit.map(item=><img key={item} className={'wear-'+item} src={url(`outfit/${item}-fitted.png`)} alt="" draggable={false}/>)}</div>}</div>})}</div>
 <p className="studio-live-status" role="status" aria-live="polite" aria-atomic="true">{announcement}</p>
 <div className="studio-dock" role="region" aria-label="소품 도구와 목록" tabIndex={editing?0:-1}>
 {editorNotice}
 {editing&&selected!==null&&<div className="size-controls"><strong>{name(selected)}</strong><label htmlFor="prop-scale">크기 {Math.round((draft[selected]?.scale??1)*100)}%</label><input id="prop-scale" aria-valuetext={Math.round((draft[selected]?.scale??1)*100)+'퍼센트'} aria-label="선택한 오브젝트 크기" type="range" min="0.5" max="2.5" step="0.1" value={draft[selected]?.scale??1} onPointerDown={()=>remember()} onKeyDown={e=>{if(e.key.startsWith("Arrow"))remember()}} onChange={e=>update(selected,{scale:Number(e.target.value)})}/><button className="secondary" onClick={()=>reorder(true)}>맨 앞으로</button><button className="secondary" onClick={()=>reorder(false)}>맨 뒤로</button>{selected!==-1&&<button className="secondary" onClick={()=>remove(selected)}>삭제</button>}</div>}
 {editing&&<><div className="studio-mode-tabs" aria-label="꾸미기 도구"><span className="studio-tray-label">내 소품</span><button className="secondary" onClick={openWardrobe}>몽쉘 꾸미기</button></div><div className="studio-tools"><div className="studio-tray"><p className="studio-instruction">소품 그림을 숲으로 끌어 놓아 봐.</p>{owned.length?<div>{owned.map(id=><button key={id} onPointerDown={e=>{if(e.pointerType!=="touch"||(e.target as HTMLElement).tagName==="IMG")start(e,id,true)}} {...handlers} onClick={e=>{if((e.nativeEvent as globalThis.PointerEvent).pointerType==='touch'&&(e.target as HTMLElement).tagName!=='IMG'){remember();update(id,{x:50,y:70});setSelected(id)}}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){remember();e.preventDefault();update(id,{x:50,y:70});setSelected(id)}}}><img src={image(id)} alt="" draggable={false}/><span>{name(id)}{draft[id]&&<small className="placement-label">배치됨</small>}</span></button>)}</div>:<p>아직 소품이 없어. 첫 버섯을 받거나 소품 상점을 열어 봐.</p>}</div></div></>}
 </div>
 {ghost!==null&&createPortal(<img ref={ghostNode} style={{transform:`translate(${ghostPoint.current.x}px,${ghostPoint.current.y}px)`}} className="studio-drag-ghost" src={image(ghost)} alt="" draggable={false}/>,document.body)}</section>
}
