import {useEffect,useRef,useState} from 'react';
import {initial,useStore,type Saved} from './store';
import {validateRecord} from './record-validation';
import {clearLesson} from './lesson-session';
export default function RecordTools(){
 const input=useRef<HTMLInputElement>(null),[pending,setPending]=useState<Saved|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{if(message.startsWith('백업 기록을 불러왔어요.')){clearLesson();window.dispatchEvent(new Event('forest-record-restored'));}},[message]);
 function download(){try{const state=useStore.getState();const data=Object.fromEntries(Object.keys(initial()).map(key=>[key,state[key as keyof Saved]]));const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,savedAt:new Date().toISOString(),data},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`word-forest-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('백업 파일을 저장했어요. 보호자 번호도 포함되니 안전하게 보관해 주세요.');}catch{setMessage('백업 파일을 만들지 못했어요. 다시 시도해 주세요.');}}
 return <section className="panel"><h2>기록 백업과 복원</h2><p>학습 기록, 도토리, 친구와 소품 배치를 파일로 보관할 수 있어요. 기기를 바꾸기 전에 백업해 주세요.</p><div className="button-row"><button className="secondary" onClick={download}>기록 파일 저장</button><button className="secondary" onClick={()=>input.current?.click()}>백업 파일 선택</button></div><input ref={input} type="file" accept="application/json,.json" hidden onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>5_000_000)throw Error();const json=JSON.parse(await file.text());if(json.version!==1)throw Error();setPending(validateRecord(json.data));setMessage('');}catch{setPending(null);setMessage('올바른 단어숲 백업 파일이 아니에요. 현재 기록은 바뀌지 않았어요.');}}}/>{pending&&<div><p>선택한 파일로 현재 기록을 바꿀까요? 먼저 현재 기록을 파일로 저장해 주세요.</p><div className="button-row"><button className="secondary" onClick={()=>setPending(null)}>취소</button><button className="primary" onClick={()=>{useStore.getState().patch(pending);setPending(null);setMessage('백업 기록을 불러왔어요. 저장 오류 안내가 없는지 확인해 주세요.');}}>이 기록으로 복원</button></div></div>}{message&&<p role="status">{message}</p>}</section>;
}
