import {create} from 'zustand';
import {get,set} from 'idb-keyval';
import {advance,dayKey,questsDone,type Progress} from './engine';
export type Saved={progress:Record<number,Progress>;acorns:number;gold:number;unlocked:number;zoneStars:Record<number,number>;friends:number[];hidden:number[];deco:number[];sound:boolean;challenge:boolean;goal:number;pin:string;dates:string[];seconds:Record<string,number>;daily:Record<string,Record<string,number>>;goldDates:string[]};
export const initial=():Saved=>({progress:{},acorns:0,gold:0,unlocked:10,zoneStars:{},friends:[],hidden:[],deco:[],sound:true,challenge:false,goal:10,pin:'',dates:[],seconds:{},daily:{},goldDates:[]});
type State=Saved&{ready:boolean;saveError:string;load:()=>Promise<void>;patch:(p:Partial<Saved>)=>void;answer:(id:number,ok:boolean,combo:number)=>void;round:(zone:number,star:number,boss:boolean,passed:boolean)=>void;tick:(n:number)=>void;reset:()=>void};
let writing=Promise.resolve();
function save(s:State){const d:Saved=Object.fromEntries(Object.keys(initial()).map(k=>[k,s[k as keyof Saved]])) as Saved;writing=writing.catch(()=>{}).then(()=>set('forest-v1',d)).catch(()=>{useStore.setState({saveError:'기기에 저장하지 못했어요. 저장 공간과 브라우저 설정을 확인해 주세요.'});});}
export const useStore=create<State>((put,take)=>({...initial(),ready:false,saveError:'',load:async()=>{try{const saved=await get<Saved>('forest-v1');put({...initial(),...saved,unlocked:10,ready:true});}catch{put({ready:true,saveError:'저장된 기록을 불러오지 못했어요. 이 창을 닫기 전에 다시 확인해 주세요.'});}},patch:p=>{put(p);save(take());},answer:(id,ok,combo)=>{const s=take(),today=dayKey(),daily={...(s.daily[today]??{})};daily.answers=(daily.answers??0)+(ok?1:0);daily.combo=Math.max(daily.combo??0,combo);const earn=questsDone(daily)&&!s.goldDates.includes(today);put({progress:{...s.progress,[id]:advance(s.progress[id],ok)},acorns:s.acorns+(ok?1:0),daily:{...s.daily,[today]:daily},dates:[...new Set([...s.dates,today])],gold:s.gold+(earn?1:0),goldDates:earn?[...s.goldDates,today]:s.goldDates});save(take());},round:(zone,star,boss,passed)=>{const s=take(),today=dayKey(),daily={...(s.daily[today]??{})};daily.rounds=(daily.rounds??0)+1;const earn=questsDone(daily)&&!s.goldDates.includes(today);put({acorns:s.acorns+5+(boss&&passed?20:0),unlocked:10,zoneStars:boss?{...s.zoneStars,[zone]:Math.max(s.zoneStars[zone]??0,star)}:s.zoneStars,friends:boss&&passed?[...new Set([...s.friends,zone])]:s.friends,daily:{...s.daily,[today]:daily},gold:s.gold+(earn?1:0),goldDates:earn?[...s.goldDates,today]:s.goldDates});save(take());},tick:n=>{const s=take(),today=dayKey();put({seconds:{...s.seconds,[today]:(s.seconds[today]??0)+n}});save(take());},reset:()=>{const pin=take().pin;put({...initial(),pin});save(take());}}));
